### ISSUE TITLE
palemoon support or derivatives?

### ISSUE THREAD

**Issue by Ygarr** [dessant/ping-blocker#4]
Please add palemoon like browsers support

**Comment by dessant** [comment]
The browser does not support the required APIs.

> WebExtensions
We will not be supporting WebExtensions of any kind in Pale Moon. Our current extension technologies provide all the features, functionality and above all API access for any extension to do anything it has to, including the limited subset that is offered by WebExtensions.

https://www.palemoon.org/roadmap.shtml
